# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""The async trainer role: consume teacher-graded trajectories, accumulate, step.

MEASURED PREMISES (job 44757670 rollout/teacher, 44758757 trainer, acc 4xH100-64G, Qwen3-1.7B
student / Qwen3-32B TP=2 teacher, periodic chunks P=3 C=50 N=10):

    role      GPU-seconds per trajectory      capacity ratio
    rollout             0.25                        7.6
    trainer             1.21                        1.6
    teacher             1.90                        1.0

Overlap is ACROSS TRAJECTORIES, never within one. Each trajectory is forwarded and backwarded
exactly once, at EOS, so the cost multiplier is 1.0. A mid-trajectory flush would re-enter the
prefix -- k flush points cost (k+1)/2 of a single pass, because log pi(y_t) depends on theta through
every layer at every position <= t -- and it buys only single-trajectory latency, which is not the
throughput metric. It is therefore deliberately absent.

ONE TRAJECTORY PER FORWARD, GRADIENTS ACCUMULATED. Three things follow, all measured:
  * EXACT. The objective is a sum and its gradient is linear over that sum, so accumulating per
    trajectory is bit-identical to the batched update (milestone 2 T1: batched == summed single-row).
  * FASTER. A padded batch forwards B x max_len tokens. Trainer throughput fell 1205 -> 899 tok/s
    from B=4 to B=16 purely because padding grew 1.42x -> 1.99x: one long trajectory sets the width
    for every other. That is the rollout's straggler effect reappearing in the trainer.
  * SMALLER. Peak memory is one trajectory's activations, not the batch's, which removes the
    20,550-token OOM ceiling that a padded batch hits on a 64 GiB card.

STALENESS IS RECORDED, NOT ASSUMED AWAY. A trajectory was generated by some policy version; by the
time it is trained on, the trainer has moved. That lag is the price of the overlap and it is the one
thing here that can quietly cost quality, so it is measured per trajectory and reported as a
distribution -- never as a mean, which hides exactly the tail that matters.
"""

import threading
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Optional


class StaleTrajectory(RuntimeError):
    """Raised when a trajectory is older than the configured bound."""


@dataclass
class Trajectory:
    """One teacher-graded trajectory, ready to train on.

    `policy_version` is the trainer's optimizer-step count at the time the ROLLOUT weights that
    generated this trajectory were published -- not when generation started, and not when the
    teacher finished. Anything else makes the staleness number mean something other than "how far
    has the policy moved since this was on-policy".
    """

    traj_id: str
    prompt_ids: list
    response_ids: list
    anchors: list
    k_sem: list
    policy_version: int
    enqueued_at: float = 0.0
    teacher_done_at: float = 0.0

    def __post_init__(self):
        if len(self.anchors) != len(self.k_sem):
            raise ValueError(f"{self.traj_id}: {len(self.anchors)} anchors but "
                             f"{len(self.k_sem)} k_sem values")
        if not self.anchors:
            raise ValueError(f"{self.traj_id}: no audited chunks; the objective would have nothing "
                             f"to reinforce")

    @property
    def tokens(self) -> int:
        return len(self.response_ids)


class ReadyQueue:
    """Bounded FIFO of teacher-graded trajectories, with backpressure.

    BOUNDED ON PURPOSE. An unbounded queue converts a trainer that cannot keep up into unbounded
    memory growth and unbounded staleness, and both of those present as something else: an OOM
    hours in, or a quality regression with no systems signal. A bounded queue makes the producer
    wait instead, which is visible in `blocked_seconds`.
    """

    def __init__(self, capacity: int = 64):
        if capacity < 1:
            raise ValueError("capacity must be >= 1")
        self.capacity = capacity
        self._q: deque = deque()
        self._lock = threading.Condition()
        self._closed = False
        self.blocked_seconds = 0.0
        self.enqueued = 0
        self.dequeued = 0
        self.depth_samples: list = []

    def put(self, t: Trajectory, timeout: Optional[float] = None) -> bool:
        with self._lock:
            t0 = time.perf_counter()
            while len(self._q) >= self.capacity and not self._closed:
                if not self._lock.wait(timeout):
                    self.blocked_seconds += time.perf_counter() - t0
                    return False
            self.blocked_seconds += time.perf_counter() - t0
            if self._closed:
                return False
            t.enqueued_at = time.perf_counter()
            self._q.append(t)
            self.enqueued += 1
            self._lock.notify_all()
            return True

    def get(self, timeout: Optional[float] = None) -> Optional[Trajectory]:
        """Returns None when the queue is closed AND drained -- the only end-of-stream signal."""
        with self._lock:
            while not self._q:
                if self._closed:
                    return None
                if not self._lock.wait(timeout):
                    return None
            self.depth_samples.append(len(self._q))
            t = self._q.popleft()
            self.dequeued += 1
            self._lock.notify_all()
            return t

    def close(self):
        with self._lock:
            self._closed = True
            self._lock.notify_all()

    def __len__(self):
        with self._lock:
            return len(self._q)


@dataclass
class AccumulationPolicy:
    """When to turn accumulated gradients into an optimizer step.

    Two triggers, because either alone misbehaves. Counting trajectories alone makes the effective
    batch size swing with response length -- 16 short trajectories and 16 long ones are not the same
    update. Counting tokens alone can stall indefinitely behind a queue that has gone quiet. Whichever
    fires first wins, and which one fired is recorded so a run can be read rather than guessed at.
    """

    trajectories_per_step: int = 16
    max_tokens_per_step: int = 0          # 0 disables the token trigger
    max_seconds_per_step: float = 0.0     # 0 disables the time trigger

    def __post_init__(self):
        if self.trajectories_per_step < 1:
            raise ValueError("trajectories_per_step must be >= 1")

    def should_step(self, n_traj: int, n_tokens: int, elapsed: float) -> Optional[str]:
        if n_traj <= 0:
            return None
        if n_traj >= self.trajectories_per_step:
            return "trajectories"
        if self.max_tokens_per_step and n_tokens >= self.max_tokens_per_step:
            return "tokens"
        if self.max_seconds_per_step and elapsed >= self.max_seconds_per_step:
            return "seconds"
        return None


class StalenessLedger:
    """Per-trajectory policy lag, kept as a distribution.

    A mean hides the tail, and the tail is the whole question: a run whose average lag is 2 steps but
    whose p99 is 200 is not a run with a lag of 2.
    """

    def __init__(self, max_lag: int = 0, drop_stale: bool = False):
        self.max_lag = max_lag              # 0 = unbounded
        self.drop_stale = drop_stale
        self.lags: list = []
        self.dropped = 0

    def admit(self, traj: Trajectory, current_version: int) -> int:
        lag = current_version - traj.policy_version
        if lag < 0:
            raise ValueError(
                f"{traj.traj_id}: policy_version {traj.policy_version} is ahead of the trainer's "
                f"{current_version}. The rollout cannot have used weights the trainer has not "
                f"published; this is a bookkeeping bug, not a stale trajectory.")
        if self.max_lag and lag > self.max_lag:
            self.dropped += 1
            if self.drop_stale:
                raise StaleTrajectory(
                    f"{traj.traj_id}: lag {lag} exceeds max_lag {self.max_lag}")
        self.lags.append(lag)
        return lag

    def summary(self) -> dict:
        if not self.lags:
            return {"n": 0, "dropped": self.dropped}
        s = sorted(self.lags)
        q = lambda f: s[min(len(s) - 1, int(f * (len(s) - 1)))]  # noqa: E731
        return {"n": len(s), "mean": sum(s) / len(s), "p50": q(.5), "p90": q(.9), "p99": q(.99),
                "max": s[-1], "dropped": self.dropped}


@dataclass
class StepRecord:
    step: int
    trajectories: int
    response_tokens: int
    chunks: int
    trigger: str
    loss: float
    l_chunk: float
    l_kl: float
    grad_norm_preclip: float
    seconds: float
    accumulate_seconds: float
    optimizer_seconds: float
    staleness: dict = field(default_factory=dict)
    peak_mem_gb: float = 0.0


class AsyncTrainer:
    """Consumes a ReadyQueue, accumulates one trajectory at a time, steps on policy.

    `ref_hidden_provider` is the seam for taking the frozen-reference forward off this role. It is
    18% of trainer time (3.33 s of 18.59 s at B=13) and the trainer is the scarce role, while the
    rollout GPU sits 93% idle. What the objective needs from the reference is HIDDEN STATES, 2048
    wide, not logits at 151936 -- about 74x less to move, ~8 MB per 1000 tokens in fp32 -- so the
    reference forward can run elsewhere and stream its result here. Left None, it is computed
    locally and the trainer pays for it.
    """

    def __init__(self, model, ref, optimizer, *, device, N=10, C=50, alpha=1.0, beta=0.1,
                 kl_slice=256, grad_clip=1.0, policy=None, staleness=None,
                 ref_hidden_provider=None, gradient_checkpointing=True):
        self.model, self.ref, self.opt = model, ref, optimizer
        self.device = device
        self.N, self.C, self.alpha, self.beta = N, C, alpha, beta
        self.kl_slice, self.grad_clip = kl_slice, grad_clip
        self.policy = policy or AccumulationPolicy()
        self.staleness = staleness or StalenessLedger()
        self.ref_hidden_provider = ref_hidden_provider
        self.gradient_checkpointing = gradient_checkpointing
        self.version = 0                      # optimizer steps published so far
        self.history: list = []

    # -- one trajectory, one forward, one backward, no padding ---------------------------------
    def accumulate_one(self, traj: Trajectory) -> dict:
        import torch
        try:                                      # as a package member
            from .omniopd_objective import omniopd_token_losses
        except ImportError:                       # or with the distillation dir on sys.path, which
            from omniopd_objective import omniopd_token_losses   # is how the scripts run it
        seq = list(traj.prompt_ids) + list(traj.response_ids)
        ids = torch.tensor([seq], dtype=torch.long, device=self.device)
        # B=1: there is no attention mask to build and no padding to forward. The padded batch this
        # replaces forwarded B x max_len tokens, which cost 1.99x the real work at B=16.
        if self.gradient_checkpointing:
            self.model.gradient_checkpointing_enable(
                gradient_checkpointing_kwargs={"use_reentrant": False})
        self.model.train()
        h_cur = self.model.model(input_ids=ids, use_cache=False).last_hidden_state
        if self.ref_hidden_provider is not None:
            h_ref = self.ref_hidden_provider(traj).to(self.device)
            if h_ref.shape[:2] != h_cur.shape[:2]:
                raise ValueError(
                    f"{traj.traj_id}: reference hidden states {tuple(h_ref.shape[:2])} do not cover "
                    f"the sequence {tuple(h_cur.shape[:2])}; a provider that silently returns a "
                    f"different length would anchor the student against the wrong positions")
        else:
            with torch.no_grad():
                h_ref = self.ref.model(input_ids=ids, use_cache=False).last_hidden_state
        rows = [{"prompt_len": len(traj.prompt_ids), "response_ids": list(traj.response_ids),
                 "anchors": list(traj.anchors), "k_sem": list(traj.k_sem)}]
        losses, m = omniopd_token_losses(h_cur, h_ref, self.model.lm_head, self.ref.lm_head, rows,
                                         N=self.N, C=self.C, alpha=self.alpha, beta=self.beta,
                                         kl_slice=self.kl_slice)
        loss = losses.sum()
        if not torch.isfinite(loss):
            raise ValueError(f"{traj.traj_id}: non-finite loss")
        # Accumulates into .grad. The objective is a sum and its gradient is linear over that sum,
        # so this is bit-identical to backwarding the same trajectories as one padded batch.
        loss.backward()
        out = {"loss": float(loss), "l_chunk": float(m["omniopd/L_chunk"]),
               "l_kl": float(m["omniopd/L_kl"]), "chunks": int(m["omniopd/n_chunks"]),
               "tokens": traj.tokens}
        del h_cur, h_ref, losses, loss
        return out

    def step(self, trigger: str, acc: dict, t_acc: float) -> StepRecord:
        import torch
        t0 = time.perf_counter()
        gn = float(torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.grad_clip))
        if gn != gn:
            raise ValueError(f"non-finite gradient norm at step {self.version}")
        self.opt.step()
        self.opt.zero_grad(set_to_none=True)
        self.version += 1
        t1 = time.perf_counter()
        rec = StepRecord(
            step=self.version, trajectories=acc["n"], response_tokens=acc["tokens"],
            chunks=acc["chunks"], trigger=trigger, loss=acc["loss"], l_chunk=acc["l_chunk"],
            l_kl=acc["l_kl"], grad_norm_preclip=gn, seconds=t1 - acc["t0"],
            accumulate_seconds=t_acc, optimizer_seconds=t1 - t0,
            staleness=self.staleness.summary(),
            peak_mem_gb=torch.cuda.max_memory_allocated(self.device) / 2**30
            if torch.cuda.is_available() else 0.0)
        self.history.append(rec)
        return rec

    def run(self, queue: ReadyQueue, max_steps: Optional[int] = None, on_step=None) -> list:
        """Drain the queue until it closes or max_steps is reached.

        A partial accumulation left when the queue closes is DISCARDED, not stepped: a final update
        built from however many trajectories happened to be in flight is a different-sized update
        than every other one in the run, and one anomalous step at the end of a training curve is
        worse than one missing step.
        """
        acc = self._fresh()
        t_acc = 0.0
        while max_steps is None or self.version < max_steps:
            traj = queue.get(timeout=1.0)
            if traj is None:
                if len(queue) == 0:
                    break
                continue
            try:
                self.staleness.admit(traj, self.version)
            except StaleTrajectory:
                continue
            t = time.perf_counter()
            r = self.accumulate_one(traj)
            t_acc += time.perf_counter() - t
            acc["n"] += 1
            for k in ("loss", "l_chunk", "l_kl", "chunks", "tokens"):
                acc[k] += r[k]
            trig = self.policy.should_step(acc["n"], acc["tokens"],
                                           time.perf_counter() - acc["t0"])
            if trig:
                rec = self.step(trig, acc, t_acc)
                if on_step:
                    on_step(rec)
                acc, t_acc = self._fresh(), 0.0
        if acc["n"]:
            self.opt.zero_grad(set_to_none=True)
        return self.history

    @staticmethod
    def _fresh():
        return {"n": 0, "loss": 0.0, "l_chunk": 0.0, "l_kl": 0.0, "chunks": 0, "tokens": 0,
                "t0": time.perf_counter()}
